# Generated by Django 2.0.4 on 2018-04-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_text', models.TextField()),
                ('that_text', models.TextField()),
            ],
            options={
                'ordering': ('this_text',),
            },
        ),
    ]
